platform :ios, '7.0'
pod 'Parse', '~> 1.2.20'
pod 'Facebook-iOS-SDK', '~> 3.16.2'
pod 'Reachability'
pod 'MBProgressHUD', '~> 0.0'
pod 'UPPlatformSDK', '~> 1.1.5'
pod 'PebbleKit', '~> 2.2.0'
pod 'TestFlightSDK', '~> 3.0.2'
pod 'UIImageEffects', '~> 0.0.1'